export const SHOW_SIDEBAR = "SHOW_SIDEBAR"
export const DATA_TAMBAH_BARANG = "DATA_TAMBAH_BARANG"
export const TAMBAH_BARANG_STATE = "TAMBAH_BARANG_STATE"
export const DATA_BARANG_JUAL = "DATA_BARANG_JUAL"
